openapi: 3.0.3
info:
  title: Audit Service API
  description: Immutable audit logging and compliance reporting
  version: 1.0.0

servers:
  - url: https://api.llm-governance.example.com/api/v1

tags:
  - name: Audit Logs
  - name: Reports

paths:
  /audit/logs:
    get:
      tags: [Audit Logs]
      summary: Query audit logs
      security: [{bearerAuth: []}]
      parameters:
        - name: user_id
          in: query
          schema: {type: string, format: uuid}
        - name: action
          in: query
          schema: {type: string}
        - name: resource_type
          in: query
          schema: {type: string}
        - name: start_date
          in: query
          schema: {type: string, format: date-time}
        - name: end_date
          in: query
          schema: {type: string, format: date-time}
        - name: limit
          in: query
          schema: {type: integer, default: 20}
        - name: offset
          in: query
          schema: {type: integer, default: 0}
      responses:
        '200':
          description: Audit logs
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: {type: boolean}
                  data:
                    type: object
                    properties:
                      logs:
                        type: array
                        items: {$ref: '#/components/schemas/AuditLog'}
                      total: {type: integer}
    post:
      tags: [Audit Logs]
      summary: Create audit log
      security: [{bearerAuth: []}]
      requestBody:
        required: true
        content:
          application/json:
            schema: {$ref: '#/components/schemas/CreateAuditLogRequest'}
      responses:
        '201':
          description: Log created

  /audit/logs/{id}:
    get:
      tags: [Audit Logs]
      summary: Get audit log
      security: [{bearerAuth: []}]
      parameters:
        - name: id
          in: path
          required: true
          schema: {type: string, format: uuid}
      responses:
        '200':
          description: Log details

  /audit/logs/{id}/verify:
    get:
      tags: [Audit Logs]
      summary: Verify log integrity
      description: Verify SHA-256 checksum of audit log
      security: [{bearerAuth: []}]
      parameters:
        - name: id
          in: path
          required: true
          schema: {type: string, format: uuid}
      responses:
        '200':
          description: Integrity verification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: {type: boolean}
                  data:
                    type: object
                    properties:
                      verified: {type: boolean}
                      checksum: {type: string}

  /audit/export:
    post:
      tags: [Audit Logs]
      summary: Export audit logs
      description: Export logs in CSV or JSON format
      security: [{bearerAuth: []}]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                format: {type: string, enum: [csv, json]}
                filters: {type: object}
      responses:
        '200':
          description: Export file
          content:
            application/csv:
              schema: {type: string, format: binary}
            application/json:
              schema: {type: object}

  /audit/reports/compliance:
    get:
      tags: [Reports]
      summary: Generate compliance report
      security: [{bearerAuth: []}]
      parameters:
        - name: start_date
          in: query
          required: true
          schema: {type: string, format: date-time}
        - name: end_date
          in: query
          required: true
          schema: {type: string, format: date-time}
      responses:
        '200':
          description: Compliance report

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    AuditLog:
      type: object
      properties:
        id: {type: string, format: uuid}
        user_id: {type: string, format: uuid}
        action: {type: string}
        resource_type: {type: string}
        resource_id: {type: string}
        details: {type: object}
        ip_address: {type: string}
        user_agent: {type: string}
        checksum: {type: string}
        created_at: {type: string, format: date-time}

    CreateAuditLogRequest:
      type: object
      required: [action, resource_type]
      properties:
        action: {type: string}
        resource_type: {type: string}
        resource_id: {type: string}
        details: {type: object}
